### ISSUE TITLE
Feedback before XMAS

### ISSUE THREAD

**Issue by markushaslinger** [WMC-AHIF-2021/Kipper-Web#14]
- I like the design of your website in general (structure & design wise)
- There are still many placeholder, lorem impsum texts - replace them
  - Especially on the main landing page!
- We are starting with JS this week so you have a go to start integrating it
  - I'm already very curious about the playground with compiler
- So no major complaints at this point, but you still have a lot of work ahead of you

**Comment by Luna-Klatzer** [comment]
Thank u for the feedback. Regarding the placeholders, at the moment they were in place to fill the void a bit and we will soon move to add the pictures and explanatory text ^^ As the main page will mainly contain pictures to show examples and be more visually appealing.
